# Generated by Django 4.1.4 on 2023-01-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('idannonce', models.AutoField(db_column='idAnnonce', primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('V', 'Vente'), ('E', 'Echange'), ('L', 'Location'), ('LV', 'Location Pour Vacances')], max_length=2)),
                ('type_bien', models.CharField(choices=[('Terrain', 'Terrain'), ('Terrain Agricole', 'Terrain Agricole'), ('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Bungalow', 'Bungalow'), ('Villa', 'Villa'), ('Loft', 'Loft'), ('Immeuble', 'Immeuble'), ('Garage', 'Garage'), ('Hangar', 'Hangar'), ('Ferme', 'Ferme'), ('Chalet', 'Chalet'), ('Parking', 'Parking'), ('Local commercial', 'Local Commercial'), ('Local industriel', 'Local Industriel')], max_length=20)),
                ('surface', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField()),
                ('date_depot', models.DateTimeField()),
            ],
            options={
                'db_table': 'annonce',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('idlocalisation', models.AutoField(primary_key=True, serialize=False)),
                ('wilaya', models.CharField(choices=[('1', 'Adrar'), ('2', 'Chlef'), ('3', 'Laghouat'), ('4', 'Oum El Bouaghi'), ('5', 'Batna'), ('6', 'Bejaia'), ('7', 'Biskra'), ('8', 'Bechar'), ('9', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tebessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Setif'), ('20', 'Saida'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbes'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Medea'), ('27', 'Mostaganem'), ('28', 'Msila'), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arreridj'), ('35', 'Boumerdes'), ('36', 'El Taref'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Ain Defla'), ('45', 'Naama'), ('46', 'Ain Temouchent'), ('47', 'Ghardaia'), ('48', 'Relizane'), ('49', 'Timimoun'), ('50', 'Bordj Badji Mokhtar'), ('51', 'Ouled Djellal'), ('52', 'Beni Abbes'), ('53', 'In Salah'), ('54', 'In Guezzam'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'Mghair'), ('58', 'Meniaa')], max_length=2)),
                ('commune', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'localisation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idpersonne', models.AutoField(db_column='idPersonne', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('est_administrateur', models.IntegerField(blank=True, null=True)),
                ('est_utilisateur', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personne',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('idphotos', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField()),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('idmessages', models.AutoField(db_column='idMessages', primary_key=True, serialize=False)),
                ('contenu_message', models.TextField()),
                ('expediteur', models.ForeignKey(db_column='expediteur', on_delete=django.db.models.deletion.CASCADE, to='app.personne')),
                ('id_annonce', models.ForeignKey(db_column='id_annonce', on_delete=django.db.models.deletion.CASCADE, to='app.annonce')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='annonce',
            name='idannonceur',
            field=models.ForeignKey(db_column='idAnnonceur', on_delete=django.db.models.deletion.CASCADE, to='app.personne'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='idlocalisation',
            field=models.ForeignKey(db_column='idLocalisation', on_delete=django.db.models.deletion.CASCADE, to='app.localisation'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='idphotos',
            field=models.ForeignKey(db_column='idPhotos', on_delete=django.db.models.deletion.PROTECT, to='app.photos'),
        ),
    ]
