# Generated by Django 4.1.4 on 2023-02-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
